// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDETsmuKXTb0dyygKOf0wJ92RQJzjdZW-M',
    appId: '1:122921292359:ios:8be9b9f0e2d0c05bef9762',
    messagingSenderId: '122921292359',
    projectId: 'cloudfirestoreex-fecd4',
    storageBucket: 'cloudfirestoreex-fecd4.appspot.com',
    iosBundleId: 'com.shazlycode.cloudfirestoreex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDETsmuKXTb0dyygKOf0wJ92RQJzjdZW-M',
    appId: '1:122921292359:ios:8be9b9f0e2d0c05bef9762',
    messagingSenderId: '122921292359',
    projectId: 'cloudfirestoreex-fecd4',
    storageBucket: 'cloudfirestoreex-fecd4.appspot.com',
    iosBundleId: 'com.shazlycode.cloudfirestoreex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnrsHzdxSv1wQ_jAAY12iXA-aFvLL9_Sk',
    appId: '1:122921292359:web:76765172aebf761cef9762',
    messagingSenderId: '122921292359',
    projectId: 'cloudfirestoreex-fecd4',
    authDomain: 'cloudfirestoreex-fecd4.firebaseapp.com',
    storageBucket: 'cloudfirestoreex-fecd4.appspot.com',
    measurementId: 'G-64W3MKEYRJ',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnrsHzdxSv1wQ_jAAY12iXA-aFvLL9_Sk',
    appId: '1:122921292359:web:76765172aebf761cef9762',
    messagingSenderId: '122921292359',
    projectId: 'cloudfirestoreex-fecd4',
    authDomain: 'cloudfirestoreex-fecd4.firebaseapp.com',
    storageBucket: 'cloudfirestoreex-fecd4.appspot.com',
    measurementId: 'G-64W3MKEYRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkLVKrvMNQNgzmypjNxFGLjbg2pOhxdgk',
    appId: '1:122921292359:android:27ff1e475b7c9d7def9762',
    messagingSenderId: '122921292359',
    projectId: 'cloudfirestoreex-fecd4',
    storageBucket: 'cloudfirestoreex-fecd4.appspot.com',
  );

}